
public class Main {
	public static Blockchain blockchain = new Blockchain();
	
	public static void main(String[] args) {
		blockchain.add( new Block("Genesis", "0") );
		blockMasterElection elector = new blockMasterElection();
		blockchain.add( new Block( "New block generated by genesis block", elector.electBlock( blockchain ).blockHash ) );
		
		new CLI(args).parse();
	}
}