import java.util.ArrayList;
import com.google.gson.GsonBuilder;

public class Main {
	
	public static ArrayList<Block> blockchain = new ArrayList<Block>();
	
	public static void main(String[] args) {
		
		//add our blocks to the block chain ArrayList:
				blockchain.add( new Block("Genesis", "0") );	
				
		//Print the whole blockchain
				String blockchainJson = new GsonBuilder()
						.setPrettyPrinting()
						.create()
						.toJson(blockchain);
				System.out.println(blockchainJson);
				
		//Supposed that we met a condition where we need to elect a block master from the blockchain
		//Add the new block created by the elected Block
				blockMasterElection elector = new blockMasterElection();
				blockchain.add( new Block( "New block generated by genesis block", elector.electBlock( blockchain ).calculateHash() ) );
		
		//Print the whole blockchain again
				blockchainJson = new GsonBuilder()
						.setPrettyPrinting()
						.create()
						.toJson(blockchain);
				
				System.out.println("\n\n" + blockchainJson);
	}
	
	public static long getBlockHeight() {
		return blockchain.size() - 1;
	}
}
